- name: Configure Internal Network
  hosts: router
  become: yes
  tasks:
    - name: update apt
      apt:
        update_cache: yes

    - name: upgrade apt
      apt:
        upgrade: dist
        purge: yes
        autoremove: yes
        
    - name: update apt
      apt:
        update_cache: yes