- name: Check OPNsense Installation
  hosts: proxy
  become: yes
  tasks:

    - name: Check if OPNsense is installed
      ansible.builtin.stat:
        path: "/etc/opnsense-release"
      register: opnsense_installed

    - name: Display OPNsense Installation Status
      debug:
        msg: "OPNsense is installed: {{ opnsense_installed.stat.exists }}"

    - name: Check if OPNsense Web UI is accessible
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}"
        method: GET
        validate_certs: no
      register: web_response
      ignore_errors: yes

    - name: Display Web UI Status
      debug:
        msg: "Web UI is accessible: {{ web_response.status == 200 }}"
