- name: Install OPNsense on Proxy Server
  hosts: proxy
  become: yes
  tasks:

    - name: Check if OPNsense is already installed
      ansible.builtin.stat:
        path: "/etc/opnsense-release"
      register: opnsense_installed

    - name: Skip installation if OPNsense is already installed
      debug:
        msg: "OPNsense is already installed. Skipping installation."
      when: opnsense_installed.stat.exists

    - name: Install necessary dependencies
      ansible.builtin.apt:
        name: 
          - curl
          - unzip
        state: present
        update_cache: yes
      when: not opnsense_installed.stat.exists

    - name: Download OPNsense Installer
      ansible.builtin.get_url:
        url: "https://mirror.dns-root.de/opnsense/releases/23.1/OPNsense-23.1-OpenSSL-amd64.img.bz2"
        dest: "/tmp/OPNsense.img.bz2"
        mode: '0644'
      when: not opnsense_installed.stat.exists

    - name: Extract OPNsense Image
      ansible.builtin.shell: |
        bunzip2 -f /tmp/OPNsense.img.bz2
      when: not opnsense_installed.stat.exists

    - name: Identify available disk for installation
      ansible.builtin.shell: "lsblk -nd -o NAME | head -n 1"
      register: disk_name
      when: not opnsense_installed.stat.exists

    - name: Flash OPNsense image to disk
      ansible.builtin.shell: |
        dd if=/tmp/OPNsense.img of=/dev/{{ disk_name.stdout }} bs=4M status=progress
      when: not opnsense_installed.stat.exists and disk_name.stdout is defined

    - name: Reboot the system if OPNsense was installed
      ansible.builtin.reboot:
        msg: "Rebooting after OPNsense installation"
      when: not opnsense_installed.stat.exists
