- name: Configure IPTables to Allow All Traffic
  hosts: routers
  become: yes
  tasks:
    # 1️⃣ iptables 패키지 설치
    - name: Install iptables-persistent
      apt:
        name: iptables-persistent
        state: present
      when: ansible_os_family == "Debian"

    # 2️⃣ 모든 인바운드, 아웃바운드 트래픽 허용
    - name: Allow all inbound and outbound traffic
      shell: |
        iptables -P INPUT ACCEPT
        iptables -P OUTPUT ACCEPT
        iptables -P FORWARD ACCEPT
        iptables -F  # 기존 규칙 삭제
        iptables-save > /etc/iptables.rules
      notify: Save iptables rules

    # 3️⃣ 부팅 시 `iptables` 규칙 유지 설정
    - name: Ensure iptables rules persist after reboot
      copy:
        dest: /etc/network/if-pre-up.d/iptables
        mode: '0755'
        content: |
          #!/bin/sh
          iptables-restore < /etc/iptables.rules

    # 4️⃣ `netfilter-persistent` 서비스 활성화
    - name: Enable netfilter-persistent
      service:
        name: netfilter-persistent
        enabled: yes
        state: restarted

    # 5️⃣ 서버 재부팅 (필요한 경우)
    - name: Reboot the server to apply iptables changes
      reboot:
        msg: "Rebooting system to apply iptables settings..."
        pre_reboot_delay: 5
        post_reboot_delay: 10

  handlers:
    - name: Save iptables rules
      shell: |
        iptables-save > /etc/iptables.rules