name: Deploy Proxy Server Configuration

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Task to run (configure_firewall, install_home_iac, install_vlan_enp1s0)'
        required: true
        default: 'install_vlan_enp1s0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Ansible & Dependencies
      - name: Install Ansible & Dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      # 3. Debug Task Selection
      - name: Debug Task Selection
        run: |
          echo "Selected Task: ${{ github.event.inputs.task }}"
          ls ansible/home_infra/

      # 4. SSH Access Test
      - name: SSH Access Test
        run: |
          echo "Testing SSH access to the proxy server"
          sshpass -p ${{ secrets.PROXY_SERVER_SSH_PW }} ssh -o StrictHostKeyChecking=no ${{ secrets.PROXY_SERVER_SSH_ID }}@${{ secrets.PROXY_SERVER_URL }} "echo SSH connection successful"

      # 5. Generate Inventory File
      - name: Generate Inventory File
        run: |
          mkdir -p ansible/home_infra/inventory
          echo "[proxy]" > ansible/home_infra/inventory/hosts.ini
          echo "${{ secrets.PROXY_SERVER_URL }} ansible_user=${{ secrets.PROXY_SERVER_SSH_ID }} ansible_password=${{ secrets.PROXY_SERVER_SSH_PW }} ansible_become=True ansible_become_user=root ansible_become_password=${{ secrets.PROXY_SERVER_SSH_PW }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ansible/home_infra/inventory/hosts.ini

      # 6. Run Playbook from ansible/home_infra directory
      - name: Run Playbook from ansible/home_infra
        run: |
          case "${{ github.event.inputs.task }}" in
            configure_firewall)
              ansible-playbook -i ansible/home_infra/inventory/hosts.ini ansible/home_infra/proxy/configure_firewall.yml --extra-vars "ansible_user=${{ secrets.PROXY_SERVER_SSH_ID }} ansible_password=${{ secrets.PROXY_SERVER_SSH_PW }} ansible_become=True ansible_become_user=root ansible_become_password=${{ secrets.PROXY_SERVER_SSH_PW }}"
              ;;
            install_vlan_enp1s0)
              ansible-playbook -i ansible/home_infra/inventory/hosts.ini ansible/home_infra/proxy/install_vlan_enp1s0.yml --extra-vars "ansible_user=${{ secrets.PROXY_SERVER_SSH_ID }} ansible_password=${{ secrets.PROXY_SERVER_SSH_PW }} ansible_become=True ansible_become_user=root ansible_become_password=${{ secrets.PROXY_SERVER_SSH_PW }}"
              ;;
            *)
              echo "Invalid task specified"
              exit 1
              ;;
          esac